### ISSUE TITLE
v5 possible? 

### ISSUE THREAD

**Issue by karlingen** [infinitered/ignite-redux-persist#4]
Can we make version 5.x for `redux-persist` possible? :)

**Comment by kumarpatel** [comment]
+1

**Comment by Amurmurmur** [comment]
@karlingen @kumarpatel 
Just updated the plugin, hopefully team will be able to merge it as soon as possible 👍 
https://github.com/infinitered/ignite-redux-persist/pull/5

**Comment by ryanlntn** [comment]
Merged! This will be landing in the ignite-ir-boilerplate shortly: https://github.com/infinitered/ignite-ir-boilerplate/pull/174
