### ISSUE TITLE
Redux persist "inactive" by default

### ISSUE THREAD

**Issue by dgptamayo** [infinitered/ignite-redux-persist#6]
Is this the desired behavior?

```
ignite new ignitePersist  130.00s user 38.49s system 39% cpu 7:11.72 total
$ cat ignitePersist/App/Config/ReduxPersist.js | grep active
  active: false,
```

Unless set to `true`, *autoRehydrate()* and *RehydrationServices.updateReducers* won't run

**Comment by ryanlntn** [comment]
@dgptamayo Good question. When I pulled this from the ignite-ir-boilerplate it was defaulting to false but now that it is a plugin it would make more sense to default to true.
